name: CI
on: push
env:
  CI: false
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - run: echo "CI= $CI"